import { IEventsResponse } from '@/services/events/interfaces';

export const eventsFallback: IEventsResponse[] = [
  {
    id: 1,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 2,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 3,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 4,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 5,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 6,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Санкт-Петербург',
    dateStart: 24,
    dateFinish: 25,
  },
  {
    id: 7,
    href: 'http:/photo.jpg',
    imgLink: 'http:/photo.jpg',
    title: 'Хакатон IT INNO HACK',
    tags: ['AI', 'Инфраструктура', 'Дизайн', 'Backend', 'Frontend', 'Lead'],
    location: 'Москва',
    dateStart: 24,
    dateFinish: 25,
  },
];
